# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip


platform :ios, 14.0
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
    Pod::UI.puts "Configuring Pod with #{linkage}ally linked frameworks".green
    use_frameworks! :linkage => linkage.to_sym
end


# source 'https://github.com/CocoaPods/Specs.git'

target 'AzureCommunicationUIDemoApp' do
  config = use_native_modules!

  pod 'AzureCommunicationUICalling', '1.6.0'
  
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'AzureCommunicationUIDemoAppTests' do
    inherit! :complete
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  #  pre_install do |installer|
  #  installer.pod_targets.each do |pod|
  #    if pod.name.eql?('RNScreens')
  #      def pod.build_type
  #        Pod::BuildType.static_library
  #      end
  #    end
  #  end

    post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
  end
end
